name: 'compile-arduino-library'
description: 'compiles the different templates to make sure they work'

# TODO: use a build matrix instead of hardcoding the combinatorial explosion.

runs:
  using: "composite"
  steps:
    - name: Download puara-gestures-arduino artifact
      uses: actions/download-artifact@v4
      with:
        name: puara-gestures-arduino

    - name: Install Arduino CLI
      shell: bash
      run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH="$PWD/bin:$PATH"
          echo "$PWD/bin" >> $GITHUB_PATH
          arduino-cli version
          arduino-cli config init
          arduino-cli core update-index

    # Install Board Cores
    - name: Install ESP32 Core
      shell: bash
      run: |
        arduino-cli core install esp32:esp32

    # Install Library Dependencies
    - name: Install Library Dependencies
      shell: bash
      run: |
        arduino-cli lib list
        arduino-cli lib install "Eigen" "boost-embedded-190"
        mkdir -p $HOME/Arduino/libraries
        ln -s $PWD $HOME/Arduino/libraries/puara
        cd ../../../../../ 
        find .

    # Compile Example Sketches for TinyPICO
    - name: Compile for TinyPICO
      shell: bash
      run: |
        arduino-cli compile --fqbn esp32:esp32:um_tinypico examples/utils/blobDetector/blobDetector.ino
